<head>
    <title>COS 80021 Web Application Development</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="keyword" content="ABN TFN tax" />
    <!-- Favicon-->
    <!-- Primary Meta Tags -->
    <meta name="title" content="Individual Business Number(ABN) application & WWCC & Police check & tax return services">
    <meta name="description" content="Application for individual Australia business number(ABN), work with children check, police check and tax return. Come visit us to find out more and get a discount.">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://metatags.io/">
    <meta property="og:title" content="Individual Business Number(ABN) application & WWCC & Police check & tax return services">
    <meta property="og:description" content="Application for individual Australia business number(ABN), work with children check, police check and tax return. Come visit us to find out more and get a discount.">
    <meta property="og:image" content="https://metatags.io/assets/meta-tags-16a33a6a8531e519cc0936fbba0ad904e52d35f34a46c97a2c9f6f7dd7d336f2.png">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://metatags.io/">
    <meta property="twitter:title" content="Individual Business Number(ABN) application & WWCC & Police check & tax return services">
    <meta property="twitter:description" content="Application for individual Australia business number(ABN), work with children check, police check and tax return. Come visit us to find out more and get a discount.">
    <meta property="twitter:image" content="https://metatags.io/assets/meta-tags-16a33a6a8531e519cc0936fbba0ad904e52d35f34a46c97a2c9f6f7dd7d336f2.png">
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap Icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anton&family=Hind:wght@500&family=M+PLUS+1p:wght@100;800&family=Open+Sans:wght@300&family=Yanone+Kaffeesatz:wght@300&display=swap" rel="stylesheet">
    <!-- SimpleLightbox plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet" />
</head>